### ISSUE TITLE
Improve location detection / save 

### ISSUE THREAD

**Issue by bagage** [nrenner/brouter-web#48]
Currently when one opens http://brouter.de/brouter-web, he always get map centered on Frankfurt with zoom level 8 or so, the first thing to do is to move the map over his own position. 
It could be great to save the last used position so that when you always bike in the same area, you do not need to re-localize yourself again. I know that permalink can solve this issue, but I'd like to know if a cookie could be saved to store position for default position (like openstreetmap.org does for instance, but also google maps)?
I'd be glad to make a PR for this if you think it's worth it! 

edit: a "localize me" button could be nice too, see [this demo](https://www.domoritz.de/leaflet-locatecontrol/demo/).

- [x] : use `Leaflet.RestoreView` plugin to save and restore last map view. Cf PR #49 
- [x] : add a `Localize me` button using `leaflet-locatecontrol` plugin. Cf PR #49

**Comment by nrenner** [comment]
It seems like there is a plugin [Leaflet.RestoreView](https://github.com/makinacorpus/Leaflet.RestoreView) for keeping the last map position.

Should be straightforward to add, I can do that, not really a need for a PR. But generally, contributions are welcome!

Using the [leaflet-locatecontrol](https://github.com/domoritz/leaflet-locatecontrol) you linked is already on my to-do list together with some basic mobile support.

**Comment by bagage** [comment]
So this issue could be split up in two:
- [x] : use `Leaflet.RestoreView` plugin to save and restore last map view. Cf PR #49 
- [ ] : add a `Localize me` button using `leaflet-locatecontrol` plugin.
Basic mobile support would be awesome indeed when you must check routes while traveling :). Looking forward for it too!
