### ISSUE TITLE
Verify Leaflet 1.0 support

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#65]
# Plugin support

- [x] [leaflet-routing](https://github.com/Turistforeningen/leaflet-routing)  
  - [[WIP] Support Leaflet 1.0 #43](https://github.com/Turistforeningen/leaflet-routing/pull/43) - using dev fork
  - [Leaflet 1.0: Removed MultiPolyline and MultiPolygon in LineUtil.Snapping.js #45](https://github.com/Turistforeningen/leaflet-routing/issues/45) - not used, probably not an issue with only LineStrings
- [x] [Leaflet.Elevation](https://github.com/MrMufflon/Leaflet.Elevation) - bower dep. `leaflet-dist: 0.7.x` - workaround in 761a053b7277e86d23384ec539fc45fe1eba7765
- [x] ~~[Leaflet.draw](https://github.com/Leaflet/Leaflet.draw) - since v0.4.0, update to v0.4.9~~ - see #100
- [x] [Leaflet.Editable](https://github.com/Leaflet/Leaflet.Editable) - "You need Leaflet >= 1.0.0"
- [x] [Leaflet Control Geocoder](https://github.com/perliedman/leaflet-control-geocoder) - Leaflet 1.0.0 badge, v1.5.4 would remove bower ~0.7.2 dep., but [#155](https://github.com/perliedman/leaflet-control-geocoder/issues/155)
- [x] [leaflet-plugins](https://github.com/shramov/leaflet-plugins) - "Tested with: Leaflet 1.0.x", update to v3.0.0
- [x] [Leaflet.EasyButton](https://github.com/CliffCloud/Leaflet.EasyButton) - "version 2.x.x and up expect Leaflet 1.x."
- [x] [Leaflet.RestoreView](https://github.com/makinacorpus/Leaflet.RestoreView) - no info, seems to work
- [x] [Leaflet.Locate](https://github.com/domoritz/leaflet-locatecontrol) - "Tested with Leaflet 1.0", update to v0.60.0
- [x] [leaflet-sidebar-v2](https://github.com/nrenner/leaflet-sidebar-v2) - "supports leaflet (0.x and 1.x)"

# breaking changes

- [x] `L.Browser.touch` - #69
- [x] [only propagate events if given true to fire, #2311](https://github.com/Leaflet/Leaflet/commit/6d1142a9780fdb8ddcc1bc947ed6307237e795dd)

My (possibly incomplete) selection of probably breaking changes from the list of API changes, see [Changelog 1.0-beta1](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md#10-beta1-july-14-2015) and later.

### API changes

- [x] Consistent GeoJSON casing (by [yohanboniface](https://github.com/yohanboniface)) [#4108](https://github.com/Leaflet/Leaflet/pull/4108)
- [x] Move `L.LatLng.equals` to `L.CRS.equals`. (by [perliedman](https://github.com/perliedman)) [#4074](https://github.com/Leaflet/Leaflet/pull/4074)

### Vectors API improvements

- [ ] Added `SVG` & `Canvas` classes that now contain all renderer-specific code for vector layers and can be added as layers to the map.
- [ ] All vector layer classes (`Path`, `Polyline`, etc.) now don't contain any renderer-specific code and instead can be passed a renderer layer to use as `renderer` in options;
- [ ] Removed `MultiPolyline` and `MultiPolygon` classes since multiple rings are now handled by `Polyline` and `Polygon` classes respectively. Layers with multiple rings now perform much better (since each is now physically a single path object instead of being a `FeatureGroup` of layers).
- [ ] Changed `Circle` to inherit from `CircleMarker` and not the other way.
- [x] Removed `Polyline` and `Polygon` `spliceLatLngs` method (just use `setLatLngs` instead).
- [ ] Changed `Polygon` `getLatLngs` to always return an array of rings (nested array) (by [yohanboniface](https://github.com/yohanboniface)). [#2618](https://github.com/Leaflet/Leaflet/issues/2618) [#3386](https://github.com/Leaflet/Leaflet/pull/3386) [Leaflet/Leaflet#3279](https://github.com/Leaflet/Leaflet/pull/3279) [#2648](https://github.com/Leaflet/Leaflet/issues/2648)
- [x] Removed `L_PREFER_CANVAS` global switch and added `Map` `preferCanvas` option instead (by [yohanboniface](https://github.com/yohanboniface)). [#3623](https://github.com/Leaflet/Leaflet/pull/3623)

### Layers API improvements

- [x] Removed `Map` `tilelayersload` event.
- [ ] Removed `Popup` `open` and `close` events in favor of `add` and `remove` for consistency.
- [ ] Moved all layer-related logic in `Map.js` to `Layer.js`.
- [x] Renamed `clickable` option to `interactive` (by [AndriiHeonia](https://github.com/AndriiHeonia)). [#2838](https://github.com/Leaflet/Leaflet/pull/2838) [#2499](https://github.com/Leaflet/Leaflet/issues/2499)

#### TileLayer API improvements

- [x] Removed `TileLayer.Canvas` in favor of the much more flexible and powerful `GridLayer`.
- [ ] Removed `url` property in `tileload` and `tileloadstart` events (get it through `tile.src`).

### Other breaking API changes

- [ ] Changed `DomUtil` `off` to require `context` attribute if you remove a listener that was previously added with a particular context.
- [x] Removed `DomUtil.getViewportOffset` method as it is no longer necessary.
- [x] Removed `DomUtil` `getTranslateString` and `getScaleString` methods.
- [x] Removed `DomUtil` `documentIsLtr` method.
- [x] Removed `LatLng` `RAD_TO_DEG`, `DEG_TO_RAD` and `MAX_MARGIN` constants.
- [x] Renamed `Util.limitExecByInterval` to `Util.throttle`.

**Comment by nrenner** [comment]
Grep to find the obvious renames and removes:
```
# bower_components list generated with "gulp log" (gulp-debug)
grep -r --include=*.js -E -f leaflet10.txt \
  js \
  bower_components/leaflet-plugins/control/Permalink.js \
  bower_components/leaflet-plugins/control/Permalink.Layer.js \
  bower_components/leaflet-plugins/layer/tile/Bing.js \
  bower_components/leaflet-routing/src/utils/LineUtil.Snapping.js \
  bower_components/leaflet-routing/src/utils/Marker.Snapping.js \
  bower_components/leaflet-routing/src/L.Routing.js \
  bower_components/leaflet-routing/src/L.Routing.Draw.js \
  bower_components/leaflet-routing/src/L.Routing.Edit.js \
  bower_components/leaflet.draw/dist/leaflet.draw-src.js \
  bower_components/leaflet.elevation/dist/leaflet.elevation-0.0.4.src.js \
  bower_components/leaflet-control-geocoder/dist/Control.Geocoder.js \
  bower_components/Leaflet.EasyButton/src/easy-button.js \
  bower_components/Leaflet.RestoreView/leaflet.restoreview.js \
  bower_components/leaflet-sidebar/src/L.Control.Sidebar.js \
  bower_components/leaflet.locatecontrol/src/L.Control.Locate.js
```

leaflet10.txt:
```
L\.geoJson
MultiPolyline
MultiPolygon
spliceLatLngs
L_PREFER_CANVAS
tilelayersload
clickable
TileLayer\.Canvas
DomUtil\.getViewportOffset
DomUtil\.getTranslateString
DomUtil\.getScaleString
DomUtil\.documentIsLtr
LatLng\.RAD_TO_DEG
LatLng\.DEG_TO_RAD
LatLng\.MAX_MARGIN
Util\.limitExecByInterval
```
