### ISSUE TITLE
PR #56 follow-up

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#66]
Collection of remaining issues after PR #56:

- [x] Chrome flex/layout issue (map height stays same) when minimizing+maximizing elevation diagram - @bagage 
- [x] Verify Leaflet 1.0 support #65 - @nrenner  
- [x] Big touch icons in Chrome - #69 - @nrenner  
  Combination of changed `L.Browser.touch` feature detect in Leaflet 1.0 and Chrome now supporting touch features on desktop - will create a separate issue
- [x] [Hover/mouseOver not working on Chrome #67](https://github.com/MrMufflon/Leaflet.Elevation/issues/67) - @nrenner
  same as above, because `L.Browser.touch` is now set in Chrome, Leaflet.Elevation [only listens](https://github.com/MrMufflon/Leaflet.Elevation/blob/05d24f4659e5d109d372c869a355ad2a900d7e79/src/L.Control.Elevation.js#L101-L116) for touch events
- [x] now with `dist` folder removed from repo, provide a convenient way for end users to run BRouter-Web offline and update readme [Install instructions](https://github.com/nrenner/brouter-web#install-brouter-web-client) accordingly
  - upload built zip with dist as release (tag) attachment?
    - complete standalone zip including BRouter server jar, profiles and [scripts](https://github.com/abrensch/brouter/tree/master/misc/scripts/standalone) (maintain in brouter-web)?
  - Leaflet commits dist folder only for release/tag, see [build/publish.sh](https://github.com/Leaflet/Leaflet/blob/703ae02aa8cbd0b87be5b01e77754b83ad732267/build/publish.sh#L21) (--force to add ignored)
  - Dockerfile?
- [x] Keep Permalink or implement Hash URL (#62) (in addition to "Share URL")  
  Otherwise users need to switch twice: first Permalink to Share URL, later to Hash URL;  
  Share URL is a visible alternative & allows easy copying, but lacks some features the Permalink has @bagage (see #74)
- [x] Custom profile in sidebar instead of Options modal (at least on desktop) @bagage (see #76)
  - [x] Separate profile and data table in sidebar - #90
- [x] Verify deleted CSS - #92
- [x] [Restore (short) attribution on the map #110](https://github.com/nrenner/brouter-web/issues/110)
- [x] [Remove unused code #111](https://github.com/nrenner/brouter-web/issues/111)
- [x] [Remembering collapsible state not working for elevation (anymore?) #112](https://github.com/nrenner/brouter-web/issues/112)
- [x] ... (more to come)

Minor
- [x] Data table does not scroll (sidebar container does), thus table header disappears - #86
- [x] Remember sidebar and elevation open/closed state (localStorage)? @bagage (see #75)

**Comment by bagage** [comment]
Thanks @nrenner for the follow-up. I'll try to fix (again) flex in the week hopefully :).

**Comment by nrenner** [comment]
I added a few more items (still need to check the rest of my review notes). 

Regarding Leaflet 1.0 I have a better feeling now and will wait a bit for feedback on the external issues. Partly because we are lacking tests, I wanted to be proactive about checking the breaking changes and have done the most obvious ones now. I'll see about rest, maybe I'll just skip these eventually, so don't wait for those items to be completed.

Next, I really should do some intermediate other work and address at least some long waiting issues and PRs in achavi. But now that the bike season is about to start, I hope we can address remaining issues/tasks and get to a releasable state sometime this spring.

**Comment by bagage** [comment]
@nrenner Is there anything left I can help on?

**Comment by nrenner** [comment]
Sure, would appreciate any help. You can basically pick any item that you feel like addressing and that is not assigned yet (without name). Ask back when unclear what I mean.

**Comment by bagage** [comment]
@nrenner I can work on permalink then :).
